---
- name: install basics
  hosts: all

  vars:

  pre_tasks:
    - name: Generate locales
      community.general.locale_gen:
        name: "{{ item }}"
        state: present
      loop: "{{ locales_gen }}"

- name: install pgsql on pgX
  hosts: pg

  roles:
    - role: pgsql

- name: install barman on bmx
  hosts: bm

  pre_tasks:
    - name: check vars
      ansible.builtin.debug:
        msg: "CHECK: {{ hostvars[item].ansible_hostname }} ; {{ hostvars[item].inventory_hostname_short }}"
      loop: "{{ groups['pg'] }}"
    - name: ipv6 prefixing
      ansible.builtin.debug:
        msg: "{{ (hostvars[item].ansible_default_ipv6.address + '/' + hostvars[item].ansible_default_ipv6.prefix) | ansible.utils.ipaddr('network/prefix') }}"
      loop: "{{ groups['pg'] }}"

  roles:
    - role: barman
