---
- name: install basics
  hosts: all

  vars:

  pre_tasks:
    - name: Generate locales
      community.general.locale_gen:
        name: "{{ item }}"
        state: present
      loop: "{{ locales_gen }}"
    - name: ipv6 prefixg
      ansible.builtin.set_fact:
        prefix6: "{{ (ansible_default_ipv6.address + '/' + ansible_default_ipv6.prefix) | ansible.utils.ipaddr('network/prefix') }}"

- name: install pgsql on pgX
  hosts: pg

  roles:
    - role: pgsql
    - role: repmgr

- name: install barman on bmx
  hosts: bm

  pre_tasks:

  roles:
    - role: barman
