---
- name: Create regmgr.conf
  ansible.builtin.template:
    dest: /etc/repmgr.conf
    src: repmgr.conf.j2

- name: Configure shared lib
  ansible.builtin.lineinfile:
    dest: /etc/postgresql/{{ pg_major_release }}/main/postgresql.conf
    regexp: "shared_preload_libraries"
    line: "shared_preload_libraries = 'repmgr'"
    state: present

- name: Restart postgres
  ansible.builtin.service:
    name: postgresql
    state: restarted

- name: Add repmgr db
  community.postgresql.postgresql_db:
    name: repmgr
    owner: repmgr

# SQL users
- name: create repmgr user
  community.postgresql.postgresql_user:
    db: postgres
    name: repmgr
    password: rep1mgr
    role_attr_flags: "SUPERUSER,REPLICATION,LOGIN"
  tags: ['never', 'users']
